import Link from "next/link";

export const metadata = {
  title: "About | 뉴MB.chat",
  description: "About 뉴MB.chat."
};

export default function AboutPage() {
  return (
    <main className="legal-page">
      <section className="legal-card">
        <Link href="/" className="back-link">
          ← Back to 뉴MB.chat
        </Link>

        <h1>About 뉴MB.chat</h1>

        <p>
          뉴MB.chat is an unofficial parody AI chat experience inspired by
          publicly available football interviews and football community culture.
        </p>

        <p>
          The service is designed for entertainment purposes. It does not
          represent, impersonate, or speak on behalf of any real person,
          football organization, team, federation, or public figure.
        </p>

        <p>
          Responses may be generated by automated systems and may include humor,
          satire, exaggeration, or fictional phrasing. They should not be treated
          as actual quotes, official statements, or factual reporting.
        </p>

        <p>
          The goal of 뉴MB.chat is simple: create short, shareable, football-style
          parody responses that people can enjoy and share.
        </p>
      </section>
    </main>
  );
}
