import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description:
    "About 뉴MB.chat, an unofficial parody AI inspired by public football interviews and football culture."
};

export default function AboutPage() {
  return (
    <main className="legal-page">
      <article className="legal-card">
        <a className="back-link" href="/">
          ← Back to 뉴MB.chat
        </a>

        <h1>About</h1>

        <p>
          뉴MB.chat is an unofficial parody AI chat experience inspired by public
          football interviews, football culture, and internet meme humor.
        </p>

        <p>
          The service generates short, fictional, comedic responses in the style
          of a dramatic football interview. It is intended for entertainment and
          meme creation.
        </p>

        <h2>Unofficial parody</h2>

        <p>
          뉴MB.chat is not affiliated with, endorsed by, sponsored by, or
          officially connected to any real person, football club, federation,
          company, or organization.
        </p>

        <p>
          Responses generated by this site are fictional parody content. They
          should not be treated as real quotes, official statements, or factual
          claims from any real person.
        </p>

        <h2>How it works</h2>

        <p>
          When you submit a question, the site may generate a response using a
          combination of local parody templates and AI-generated text. Some
          common questions may be answered from local templates to improve speed
          and reduce cost.
        </p>

        <p>
          Users can also create shareable meme-style images from generated
          responses, including poster-style and chat-style images.
        </p>

        <h2>Contact</h2>

        <p>
          For questions about this site, please contact the site operator at:
          contact@newmb.chat
        </p>
      </article>
    </main>
  );
}
